FROM python:3.8-slim-buster

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DockerHOME=/home/app/web

RUN mkdir -p $DockerHOME
WORKDIR $DockerHOME

COPY . .

RUN pip install --upgrade pip && pip install -r requirements/production.txt

EXPOSE 8000