version: "3.8"

services:
    web:
        build: .
        ports:
            - "8000:8000"
        tty: true
        environment:
            - DJANGO_ENV=production
            - DEBUG=False
    
    database:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: ""

    celery-backend:
        image: redis

    message-broker:
        image: rabbitmq
