version: '3.9'

services:
    web:
        container_name: recycle_web
        image: recycle
        build:
            context: .
            dockerfile: Dockerfile.prod 
        ports:
            - "8000:8000"
        volumes:
            - static-data:/home/app/web/static
        depends_on:
            - db
        env_file:
            - ./config/envs/.env.prod
        environment:
            - DB_PASSWORD=""
        command: wait-for-it --service db:5432 -- gunicorn config.wsgi:application --bind 0.0.0.0:8000

    db:
        container_name: recycle_db
        image: postgres
        ports:
            - "5432:5432"
        restart: always
        volumes:
            - postgres-data:/var/lib/postgresql/data/
        env_file:
            - ./config/envs/.env.prod.db
        environment:
            - POSTGRES_PASSWORD=""
    
    nginx:
        container_name: recycle_nginx
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "1995:80"
        volumes:
            - static-data:/home/app/web/static
        depends_on:
            - web
        restart: "on-failure"

volumes:
    postgres-data:
    static-data:
